REPLACE INTO `mangos_string` (`entry`, `content_default`, `content_loc4`)
VALUES
	(1, 'You should select a character or a creature.', '你应该选择一个玩家或生物.'),
	(2, 'You should select a creature.', '你应该选择一个生物.'),
	(3, '|cffff0000[System Message]: %s|r', '|cffff0000[系统消息]: %s|r'),
	(4, '|cffff0000[Event Message]: %s|r', '|cffff0000[事件消息]: %s|r'),
	(5, 'There is no help for that command', '该命令没有帮助信息'),
	(6, 'There is no such command', '没有这个命令'),
	(7, 'There is no such subcommand', '没有这个子命令'),
	(8, 'Command %s have subcommands:', '命令 %s 有以下子命令: '),
	(9, 'Commands available to you:', '你可用的命令: '),
	(10, 'Incorrect syntax.', '错误的命令语法.'),
	(11, 'Your account level is: %i', '你的帐号等级是: %i'),
	(12, 'Online players: %u (max: %u) Queued players: %u (max: %u)', '在线玩家: %u (最大: %u) 排队玩家: %u (最大: %u)'),
	(13, 'Server uptime: %s', '服务器正常运行时间: %s'),
	(14, 'Player saved.', '玩家已保存.'),
	(15, 'All players saved.', '所有玩家已保存.'),
	(16, 'There are the following active GMs on this server:', '服务器上有以下活跃 GM: '),
	(17, 'There are no GMs currently logged in on this server.', '服务器上当前没有 GM 登录.'),
	(18, 'Cannot do that while flying.', '飞行的时候不能那么做.'),
	(19, 'Cannot do that in Battlegrounds.', '战场中不能那么做.'),
	(20, 'Target is flying you can\'t do that.', '目标正在飞行，你不能那么做.'),
	(21, '%s is flying command failed.', '%s 正在飞行，命令执行失败.'),
	(22, 'You are not mounted so you can\'t dismount.', '你没有上马因此你不能下马.'),
	(23, 'Cannot do that while fighting.', '战斗中不能那么做.'),
	(24, 'You used it recently.', '你最近使用过它.'),
	(25, 'Password not changed (unknown error)!', '密码未更新 (未知错误)!'),
	(26, 'The password was changed', '密码已更新'),
	(27, 'The old password is wrong', '旧密码错误'),
	(28, 'Your account is now locked.', '你的帐号现在被锁定.'),
	(29, 'Your account is now unlocked.', '你的帐号现在已解锁.'),
	(30, ', rank ', ', 级别 '),
	(31, ' [known]', ' [已知]'),
	(32, ' [learn]', ' [学习]'),
	(33, ' [passive]', ' [被动]'),
	(34, ' [talent]', ' [天赋]'),
	(35, ' [active]', ' [活动]'),
	(36, ' [complete]', ' [完成]'),
	(37, ' (offline)', ' (离线)'),
	(38, 'on', '开'),
	(39, 'off', '关'),
	(40, 'You are: %s', '你是: %s'),
	(41, 'visible', '可见的'),
	(42, 'invisible', '不可见的'),
	(43, 'done', '完成'),
	(44, 'You', '你'),
	(45, ' <unknown> ', ' <未知> '),
	(46, '<error>', '<错误>'),
	(47, '<non-existing character>', '<不存在的玩家角色>'),
	(48, 'UNKNOWN', '未知'),
	(49, 'You must be at least level %u to enter.', '你必须至少到%u级才能进入.'),
	(50, 'You must be at least level %u and have item %s to enter.', '你必须至少到%u级并且具有物品%s才能进入.'),
	(51, 'Hello! Ready for some training?', '你好! 准备好做些训练了吗?'),
	(52, 'Invaid item count (%u) for item %u', '物品%u的物品数量(%u)无效'),
	(53, 'Mail can\'t have more %u item stacks', '邮箱不能再放%u物品堆叠'),
	(54, 'The new passwords do not match', '新密码不匹配'),
	(55, 'Your password can\'t be longer than 16 characters (client limit), password not changed!', '你的密码不能超过16个字符(客户端限制), 密码未更新!'),
	(56, 'Current Message of the day: %s', '当前服务器公告: %s'),
	(57, 'Using World DB: %s', '使用世界数据库: %s'),
	(58, 'Using script library: %s', '使用脚本库: %s'),
	(59, 'Using creature EventAI: %s', '使用生物 EventAI: %s'),
	(61, 'Username: ', '用户名: '),
	(62, 'Password: ', '密码: '),
	(63, 'Accepts whispers', '接受密语'),
	(64, 'Doesn\'t accept whispers', '不接受密语'),
	(65, 'Using script library: <Unknown Script Library>', '使用脚本库: <未知脚本库>'),
	(66, 'Using script library: <No Script Library Loaded>', '使用脚本库: <没有加载脚本库>'),
	(100, 'Global notify: ', '全局通知: '),
	(101, 'Map: %u (%s) Zone: %u (%s) Area: %u (%s)X: %f Y: %f Z: %f Orientation: %fgrid[%u,%u]cell[%u,%u] InstanceID: %u ZoneX: %f ZoneY: %fGroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)', NULL),
	(102, '%s is already being teleported.', '%s 已经被传送.'),
	(103, 'You can summon a player to your instance only if he is in your party with you as leader.', NULL),
	(104, 'You cannot go to the player\'s instance because you are in a party now.', NULL),
	(105, 'You can go to the player\'s instance while not being in his party only if your GM mode is on.', NULL),
	(106, 'You can not go to player %s from instance to instance.', NULL),
	(107, 'You can not summon player %s from instance to instance.', NULL),
	(108, 'You are summoning %s%s.', '正在召唤%s%s.'),
	(109, 'You are being summoned by %s.', '你正被%s召唤.'),
	(110, 'You are teleporting %s%s to %s.', '你正在传送%s%s到%s.'),
	(111, 'You are being teleported by %s.', '你正被%s传送.'),
	(112, 'Player (%s) does not exist.', '玩家(%s)不存在.'),
	(113, 'Appearing at %s\'s location.', '出现在%s的位置.'),
	(114, '%s is appearing to your location.', '%s正出现在你的位置.'),
	(115, 'Incorrect values.', '错误的值.'),
	(116, 'No character selected.', '没有选择玩家角色.'),
	(117, '%s is not in a group.', '%s 不在队伍中.'),
	(118, 'You changed HP of %s to %i/%i.', NULL),
	(119, '%s changed your HP to %i/%i.', NULL),
	(120, 'You changed MANA of %s to %i/%i.', NULL),
	(121, '%s changed your MANA to %i/%i.', NULL),
	(122, 'You changed ENERGY of %s to %i/%i.', NULL),
	(123, '%s changed your ENERGY to %i/%i.', NULL),
	(124, 'Current energy: %u', NULL),
	(125, 'You changed rage of %s to %i/%i.', NULL),
	(126, '%s changed your rage to %i/%i.', NULL),
	(127, 'You changed level of %s to %i.', NULL),
	(128, 'GUID %i, faction is %i, flags is %i, npcflag is %i, DY flag is %i', NULL),
	(129, 'Wrong faction: %u (not found in factiontemplate.dbc).', NULL),
	(130, 'You changed GUID=%i \'s Faction to %i, flags to %i, npcflag to %i, dyflag to %i.', NULL),
	(131, 'You changed the %s spellmod %u to value %i for spell with family bit %u for %s.', NULL),
	(132, '%s changed your spellmod %u to value %i for spell with family bit %u.', NULL),
	(133, '%s has access to all taxi nodes now (until logout).', NULL),
	(134, '%s has no more access to all taxi nodes now (only visited accessible).', NULL),
	(135, '%s has given you access to all taxi nodes (until logout).', NULL),
	(136, '%s has removed access to all taxi nodes (only visited still accessible).', NULL),
	(137, 'You set all speeds to %2.2f from normal of %s.', NULL),
	(138, '%s set all your speeds to %2.2f from normal.', NULL),
	(139, 'You set the speed to %2.2f from normal of %s.', NULL),
	(140, '%s set your speed to %2.2f from normal.', NULL),
	(141, 'You set the swim speed to %2.2f from normal of %s.', NULL),
	(142, '%s set your swim speed to %2.2f from normal.', NULL),
	(143, 'You set the backwards run speed to %2.2f from normal of %s.', NULL),
	(144, '%s set your backwards run speed to %2.2f from normal.', NULL),
	(147, 'You set the size %2.2f of %s.', NULL),
	(148, '%s set your size to %2.2f.', NULL),
	(149, 'There is no such mount.', NULL),
	(150, 'You give a mount to %s.', NULL),
	(151, '%s gave you a mount.', NULL),
	(152, 'USER1: %i, ADD: %i, DIF: %i', NULL),
	(153, 'You take all copper of %s.', NULL),
	(154, '%s took you all of your copper.', NULL),
	(155, 'You take %i copper from %s.', NULL),
	(156, '%s took %i copper from you.', NULL),
	(157, 'You give %i copper to %s.', NULL),
	(158, '%s gave you %i copper.', NULL),
	(159, 'You hear sound %u.', NULL),
	(160, 'USER2: %i, ADD: %i, RESULT: %i', NULL),
	(161, 'Removed bit %i in field %i.', NULL),
	(162, 'Set bit %i in field %i.', NULL),
	(163, 'Teleport location table is empty!', NULL),
	(164, 'Teleport location not found!', NULL),
	(165, 'Requires search parameter.', NULL),
	(166, 'There are no teleport locations matching your request.', NULL),
	(168, 'Locations found are: %s', NULL),
	(169, 'Mail sent to %s', NULL),
	(170, 'You try to hear sound %u but it doesn\'t exist.', NULL),
	(171, 'You can\'t teleport self to self!', NULL),
	(172, 'server console command', NULL),
	(175, 'Liquid level: %f, ground: %f, type flags %u, status: %d.', NULL),
	(200, 'No selection.', NULL),
	(201, 'Object GUID is: %s', NULL),
	(202, 'The name was too long by %i characters.', NULL),
	(203, 'Error, name can only contain characters A-Z and a-z.', NULL),
	(204, 'The subname was too long by %i characters.', NULL),
	(205, 'Not yet implemented', NULL),
	(206, 'Item \'%i\' \'%s\' added to list with maxcount \'%i\' and incrtime \'%i\'', NULL),
	(207, 'Item \'%i\' not found in database.', NULL),
	(208, 'Item \'%i\' \'%s\' deleted from vendor list', NULL),
	(209, 'Item \'%i\' not found in vendor list.', NULL),
	(210, 'Item \'%i\' already in vendor list.', NULL),
	(211, 'Spells of %s reset.', NULL),
	(212, 'Spells of %s will reset at next login.', NULL),
	(213, 'Talents of %s reset.', NULL),
	(214, 'Talents of %s will reset at next login.', NULL),
	(215, 'Your spells have been reset.', NULL),
	(216, 'Your talents have been reset.', NULL),
	(217, 'Unknown case \'%s\' for .resetall command. Type full correct case name.', NULL),
	(218, 'Spells will reset for all players at login. Strongly recommend re-login!', NULL),
	(219, 'Talents will reset for all players at login. Strongly recommend re-login!', NULL),
	(240, 'File imported.', NULL),
	(239, 'No waypoints found inside the database.', NULL),
	(237, 'Waypoint %s modified.', NULL),
	(238, 'WP export successfull.', NULL),
	(235, 'UNUSED', NULL),
	(236, 'Waypoint changed.', NULL),
	(234, 'Added Waypoint %u to %s (PathId %i, path stored by %s)', NULL),
	(233, 'Argument required for \'%s\'.', NULL),
	(232, 'No waypoint number provided.', NULL),
	(231, 'No GUID provided.', NULL),
	(230, 'Could not add waypoint %u to %s (pathId %i stored by %s)', NULL),
	(229, 'All visual waypoints removed', NULL),
	(228, 'Could not create visual waypoint with creatureID: %d', NULL),
	(227, 'No visual waypoints found', NULL),
	(226, 'You must select a visual waypoint.', NULL),
	(225, 'Creature (GUID: %u) not found', NULL),
	(224, 'Cannot access %s on map, maybe you are too far away from its spawn location', NULL),
	(223, 'Creature (GUID: %u) No waypoints found - This is a MaNGOS db problem (single float).', NULL),
	(222, '%s has no path or path empty, path-id %i (loaded from %s)', NULL),
	(221, 'Last Waypoint not found for %s', NULL),
	(220, 'Cannot find waypoint id %u for %s (in path %i, loaded from %s)', NULL),
	(253, 'Forced rename for player %s will be requested at next login.', NULL),
	(254, 'Forced rename for player %s (GUID #%u) will be requested at next login.', NULL),
	(255, 'Waypoint-Creature (GUID: %u) Not found', NULL),
	(256, 'Could not find NPC...', NULL),
	(257, 'Creature movement type set to \'%s\', waypoints removed (if any).', NULL),
	(258, 'Creature movement type set to \'%s\', waypoints were not removed.', NULL),
	(259, 'Incorrect value, use on or off', NULL),
	(260, 'Value saved.', NULL),
	(261, 'Value saved, you may need to rejoin or clean your client cache.', NULL),
	(262, 'Areatrigger ID %u not found!', NULL),
	(263, 'Target map or coordinates is invalid (X: %f Y: %f MapId: %u)', NULL),
	(264, 'Zone coordinates is invalid (X: %f Y: %f AreaId: %u)', NULL),
	(265, 'Zone %u (%s) is part of instanceable map %u (%s)', NULL),
	(266, 'Nothing found!', NULL),
	(267, 'Object not found!', NULL),
	(268, 'Creature not found!', NULL),
	(270, 'Creature Removed', NULL),
	(271, 'Creature moved.', NULL),
	(272, 'Creature (GUID:%u) must be on the same map as player!', NULL),
	(273, 'Game Object (GUID: %u) not found', NULL),
	(274, 'Game Object (GUID: %u) has references in not found owner %s GO list, can\'t be deleted.', NULL),
	(275, 'Game Object (GUID: %u) removed', NULL),
	(276, 'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) turned', NULL),
	(277, 'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) moved', NULL),
	(278, 'You must select a vendor', NULL),
	(279, 'You must send id for item', NULL),
	(280, 'Vendor has too many items (max 128)', NULL),
	(281, 'You can\'t kick self, logout instead', NULL),
	(282, 'Player %s kicked.', '玩家%s被踢出服务器.'),
	(284, 'Accepting Whisper: %s', '接受密语: %s'),
	(285, 'Accepting Whisper: ON', '接受密语: 开'),
	(286, 'Accepting Whisper: OFF', '接受密语: 关'),
	(287, 'Creature (GUID: %u) not found', NULL),
	(288, 'Tickets count: %i show new tickets: %s', NULL),
	(289, 'New ticket from %s', NULL),
	(290, 'Ticket of %s (Last updated: %s):%s ', NULL),
	(291, 'New ticket show: ON', NULL),
	(292, 'New ticket show: OFF', NULL),
	(293, 'Ticket %i doesn\'t exist', NULL),
	(294, 'All tickets deleted.', NULL),
	(295, 'Character %s ticket deleted.', NULL),
	(296, 'Ticket deleted.', NULL),
	(297, 'Spawn distance changed to: %f', NULL),
	(298, 'Spawn time changed to: %i', NULL),
	(299, 'The %s field of %s was set to %u', NULL),
	(300, 'Your chat has been disabled for %u minutes.', '你被禁言%u分钟.'),
	(301, 'You have disabled %s\'s chat for %u minutes.', '你已禁言%s%u分钟.'),
	(302, 'Player\'s chat is already enabled.', '玩家禁言已解除.'),
	(303, 'Your chat has been enabled.', '你的禁言已解除.'),
	(304, 'You have enabled %s\'s chat.', '你解除了%s的禁言.'),
	(305, 'Faction %s (%u) reputation of %s was set to %5d!', NULL),
	(307, 'No faction found!', NULL),
	(308, 'Faction %i unknown!', NULL),
	(309, 'Invalid parameter %s', NULL),
	(310, 'delta must be between 0 and %d (inclusive)', NULL),
	(311, '%d - |cffffffff|Hfaction:%d|h[%s]|h|r', NULL),
	(312, ' [visible]', NULL),
	(313, ' [at war]', NULL),
	(314, ' [peace forced]', NULL),
	(315, ' [hidden]', NULL),
	(316, ' [invisible forced]', NULL),
	(317, ' [inactive]', NULL),
	(318, 'Hated', NULL),
	(319, 'Hostile', NULL),
	(320, 'Unfriendly', NULL),
	(321, 'Neutral', NULL),
	(322, 'Friendly', NULL),
	(323, 'Honored', NULL),
	(324, 'Revered', NULL),
	(325, 'Exalted', NULL),
	(326, 'Faction %s (%u) can\'not have reputation.', NULL),
	(327, ' [no reputation]', NULL),
	(328, 'Characters at account %s (Id: %u)', NULL),
	(329, '  %s (GUID %u)', NULL),
	(330, 'No players found!', NULL),
	(331, 'Extended item cost %u not exist', NULL),
	(332, 'GM mode is ON', NULL),
	(333, 'GM mode is OFF', NULL),
	(334, 'GM Chat Badge is ON', NULL),
	(335, 'GM Chat Badge is OFF', NULL),
	(336, 'You repair all %s\'s items.', NULL),
	(337, 'All your items repaired by %s.', NULL),
	(338, 'You set waterwalk mode %s for %s.', NULL),
	(339, 'Your waterwalk mode %s by %s.', NULL),
	(340, '%s is now following you.', NULL),
	(341, '%s is not following you.', NULL),
	(342, '%s is now not following you.', NULL),
	(343, 'Creature (Entry: %u) cannot be tamed.', NULL),
	(344, 'You already have pet.', NULL),
	(347, 'TaxiNode ID %u not found!', NULL),
	(348, 'Game Object (Entry: %u) have invalid data and can\'t be spawned', NULL),
	(357, 'Areatrigger %u not has target coordinates', NULL),
	(358, 'No areatriggers found!', NULL),
	(359, '%s|cffffffff|Hareatrigger_target:%u|h[Trigger target %u]|h|r Map %u X:%f Y:%f Z:%f%s', NULL),
	(360, '%s[Trigger target %u] Map %u X:%f Y:%f Z:%f', NULL),
	(361, '|cffffffff|Hareatrigger:%u|h[Trigger %u]|h|r Map %u X:%f Y:%f Z:%f%s%s%s', NULL),
	(362, '[Trigger %u] Map %u X:%f Y:%f Z:%f%s%s', NULL),
	(363, ' (Dist %f)', NULL),
	(364, ' [Tavern]', NULL),
	(365, ' [Quest]', NULL),
	(366, 'Explore quest:', '探索任务'),
	(367, 'Required level %u', '需要等级%u'),
	(368, 'Required Items:', '需要物品:'),
	(369, 'Required quest:', '需要任务'),
	(373, 'Response:\n%s ', '返回结果:\n%s'),
	(374, 'Tickets count: %i\n', NULL),
	(375, 'Player %s not have tickets.', NULL),
	(376, '%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u', NULL),
	(377, 'No pools found for map \'%s\' (Id:%u)', NULL),
	(378, 'You can\'t use this command at non-instanceable map \'%s\' (Id:%u). Use .lookup pool command instead.', NULL),
	(379, 'You can\'t use this command without args at non-instanceable map \'%s\' (Id:%u).', NULL),
	(380, '%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s', NULL),
	(381, '%d%s - [%s] X:%f Y:%f Z:%f MapId:%d Chance:%f %s', NULL),
	(382, '%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s', NULL),
	(383, '%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s', NULL),
	(384, '%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s', NULL),
	(385, '%d%s - [%s] X:%f Y:%f Z:%f MapId:%d Chance:%f %s', NULL),
	(386, '%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s', NULL),
	(387, '%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s', NULL),
	(388, 'Creatures with explicitly chance:', NULL),
	(389, 'Creatures with equal chance:', NULL),
	(390, 'Gameobjects with explicitly chance:', NULL),
	(391, 'Gameobjects with equal chance:', NULL),
	(392, 'Pool %u - Mother pool: %u |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u', NULL),
	(393, 'Pool %u - Mother pool: %u [%s] AutoSpawn: %u MaxLimit: %u', NULL),
	(394, 'Pool %u - Mother pool: none AutoSpawn: %u MaxLimit: %u', NULL),
	(395, 'No pools found', NULL),
	(396, '%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u', NULL),
	(397, 'Pools with explicitly chance:', NULL),
	(398, 'Pools with equal chance:', NULL),
	(399, '%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s', NULL),
	(400, '|cffff0000[System Message]:|rScripts reloaded', NULL),
	(401, 'You change security level of account %s to %i.', NULL),
	(402, '%s changed your security level to %i.', NULL),
	(403, 'You have low security level for this.', NULL),
	(404, 'Creature movement disabled.', NULL),
	(405, 'Creature movement enabled.', NULL),
	(406, 'Weather can\'t be changed for this zone.', NULL),
	(407, 'Weather system disabled at server.', NULL),
	(408, '%s is banned for %s. Reason: %s.', '%s 被封号%s. 原因: %s.'),
	(409, '%s is banned permanently for %s.', '%s 被永久封号%s.'),
	(410, '%s %s not found', '%s %s 未找到'),
	(411, '%s unbanned.', '%s已解封.'),
	(412, 'There was an error removing the ban on %s.', NULL),
	(413, 'Account not exist: %s', NULL),
	(414, 'There is no such character.', NULL),
	(415, 'There is no such IP in banlist.', NULL),
	(416, 'Account %s has never been banned', NULL),
	(417, 'Ban history for account %s:', NULL),
	(418, 'Ban Date: %s Bantime: %s Still active: %s  Reason: %s Set by: %s', NULL),
	(419, 'Inf.', NULL),
	(420, 'Never', NULL),
	(421, 'Yes', NULL),
	(422, 'No', NULL),
	(423, 'IP: %sBan Date: %sUnban Date: %sRemaining: %sReason: %sSet by: %s', NULL),
	(424, 'There is no matching IPban.', NULL),
	(425, 'There is no matching account.', NULL),
	(426, 'There is no banned account owning a character matching this part.', NULL),
	(427, 'The following IPs match your pattern:', NULL),
	(428, 'The following accounts match your query:', NULL),
	(429, 'You learned many spells/skills.', NULL),
	(430, 'You learned all spells for class.', NULL),
	(431, 'You learned all talents for class.', NULL),
	(432, 'You learned all languages.', NULL),
	(433, 'You learned all craft skills and recipes.', NULL),
	(434, 'Could not find \'%s\'', NULL),
	(435, 'Invalid item id: %u', NULL),
	(436, 'No items found!', NULL),
	(437, 'Invalid gameobject id: %u', NULL),
	(438, 'Found items %u: %u ( inventory %u mail %u auction %u guild %u)', NULL),
	(439, 'Found gameobjects %u: %u ', NULL),
	(440, 'Invalid creature id: %u', NULL),
	(441, 'Found creatures %u: %u ', NULL),
	(442, 'No area found!', NULL),
	(443, 'No item sets found!', NULL),
	(444, 'No skills found!', NULL),
	(445, 'No spells found!', NULL),
	(446, 'No quests found!', NULL),
	(447, 'No creatures found!', NULL),
	(448, 'No gameobjects found!', NULL),
	(449, 'Graveyard #%u doesn\'t exist.', NULL),
	(450, 'Graveyard #%u already linked to zone #%u (current).', NULL),
	(451, 'Graveyard #%u linked to zone #%u (current).', NULL),
	(452, 'Graveyard #%u can\'t be linked to subzone or not existed zone #%u (internal error).', NULL),
	(454, 'No faction in Graveyard with id= #%u , fix your DB', NULL),
	(455, 'invalid team, please fix database', NULL),
	(456, 'any', NULL),
	(457, 'alliance', NULL),
	(458, 'horde', NULL),
	(459, 'Graveyard #%u (faction: %s) is nearest from linked to zone #%u.', NULL),
	(460, 'Zone #%u doesn\'t have linked graveyards.', NULL),
	(461, 'Zone #%u doesn\'t have linked graveyards for faction: %s.', NULL),
	(462, 'Teleport location already exists!', NULL),
	(463, 'Teleport location added.', NULL),
	(464, 'Teleport location NOT added: database error.', NULL),
	(465, 'Teleport location deleted.', NULL),
	(466, 'No taxinodes found!', NULL),
	(467, 'Target unit has %d auras:', NULL),
	(468, 'id: %d eff: %d type: %d duration: %d maxduration: %d name: %s%s%s caster: %s', NULL),
	(469, 'Target unit has %d auras of type %d:', NULL),
	(470, 'id: %d eff: %d name: %s%s%s caster: %s', NULL),
	(471, 'Quest %u not found.', NULL),
	(472, 'Quest %u started from item. For correct work, please, add item to inventory and start quest in normal way: .additem %u', NULL),
	(473, 'Quest removed.', NULL),
	(474, ' [rewarded]', NULL),
	(475, ' [complete]', NULL),
	(476, ' [active]', NULL),
	(477, '%s\'s Fly Mode %s', NULL),
	(478, 'Opcode %u sent to %s', NULL),
	(479, 'Character loaded successfully!', NULL),
	(480, 'Failed to load the character!', NULL),
	(481, 'Character dumped successfully!', NULL),
	(482, 'Character dump failed!', NULL),
	(483, 'Spell %u broken and not allowed to cast or learn!', NULL),
	(484, 'Skill %u (%s) for player %s set to %u and current maximum set to %u (without permanent (talent) bonuses).', NULL),
	(485, 'Player %s must have skill %u (%s) before using this command.', NULL),
	(486, 'Invalid skill id (%u)', NULL),
	(487, 'You learned default GM spells/skills.', NULL),
	(488, 'You already know that spell.', NULL),
	(489, 'Target(%s) already know that spell.', NULL),
	(490, '%s doesn\'t know that spell.', NULL),
	(491, 'You already forgot that spell.', NULL),
	(492, 'All spell cooldowns removed for %s.', NULL),
	(493, 'Spell %u cooldown removed for %s.', NULL),
	(494, 'Command : Additem, itemId = %i, amount = %i', NULL),
	(495, 'Command : Additemset, itemsetId = %i', NULL),
	(496, 'Removed itemID = %i, amount = %i from %s', NULL),
	(497, 'Cannot create item \'%i\' (amount: %i)', NULL),
	(498, 'You need to provide a guild name!', NULL),
	(499, 'Player not found!', NULL),
	(500, 'Player already has a guild!', NULL),
	(501, 'Guild not created! (already exists?)', NULL),
	(502, 'No items from itemset \'%u\' found.', NULL),
	(503, 'The distance is: (3D) %f (2D) %f - (3D, point-to-point) %f yards.', NULL),
	(504, 'Item \'%i\' \'%s\' Item Slot %i', NULL),
	(505, 'Item \'%i\' doesn\'t exist.', NULL),
	(506, 'Item \'%i\' \'%s\' Added to Slot %i', NULL),
	(507, 'Item save failed!', NULL),
	(508, '%d - owner: %s (guid: %u account: %u ) %s', NULL),
	(509, '%d - sender: %s (guid: %u account: %u ) receiver: %s (guid: %u account: %u ) %s', NULL),
	(510, '%d - owner: %s (guid: %u account: %u ) %s', NULL),
	(511, 'Wrong link type!', NULL),
	(512, '%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0|h[%s]|h|r %s', NULL),
	(513, '%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s', NULL),
	(514, '%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ', NULL),
	(515, '%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ', NULL),
	(516, '%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ', NULL),
	(517, '%d%s, Entry %d - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r', NULL),
	(518, '%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ', NULL),
	(519, '|cffffffff|Htele:%s|h[%s]|h|r ', NULL),
	(520, '%d - |cffffffff|Hspell:%d|h[%s]|h|r ', NULL),
	(521, '%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s', NULL),
	(522, 'Game Object (Entry: %u) not found', NULL),
	(523, '>> Game Object %s (GUID: %u) at %f %f %f. Orientation %f.', NULL),
	(524, 'Selected object:|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %uX: %f Y: %f Z: %f MapId: %uOrientation: %f', NULL),
	(525, '>> Add Game Object \'%i\' (%s) (GUID: %i) added at \'%f %f %f\'.', NULL),
	(526, '%s (lowguid: %u) movement generators stack:', NULL),
	(527, '   Idle', NULL),
	(528, '   Random', NULL),
	(529, '   Waypoint', NULL),
	(530, '   Animal random', NULL),
	(531, '   Confused', NULL),
	(532, '   Targeted to player %s (lowguid %u)', NULL),
	(533, '   Targeted to creature %s (lowguid %u)', NULL),
	(534, '   Targeted to <NULL>', NULL),
	(535, '   Home movement to (X:%f Y:%f Z:%f)', NULL),
	(536, '   Home movement used for player?!?', NULL),
	(537, '   Taxi flight', NULL),
	(538, '   Unknown movement generator (%u)', NULL),
	(539, 'Player selected: %s.\nFaction: %u.\nnpcFlags: %u.\nEntry: %u.\nDisplayID: %u (Native: %u).', NULL),
	(540, 'Level: %u.', '等级: %u.'),
	(541, 'Health (base): %u. (max): %u. (current): %u.', NULL),
	(542, 'Unit Flags: %u.\nDynamic Flags: %u.\nFaction Template: %u.', NULL),
	(543, 'Loot: %u Pickpocket: %u Skinning: %u', NULL),
	(544, 'Position: %f %f %f.', NULL),
	(545, '*** Is a vendor!', NULL),
	(546, '*** Is a trainer!', NULL),
	(547, 'InstanceID: %u', NULL),
	(548, 'Player%s %s (guid: %u) Account: %s (id: %u) GMLevel: %u E-mail: %s Last IP: %s Last login: %s Latency: %ums', NULL),
	(549, 'Played time: %s Level: %u Money: %ug%us%uc', NULL),
	(550, 'Command .pinfo doesn\'t support \'rep\' option for offline players.', NULL),
	(551, '%s has explored all zones now.', NULL),
	(552, '%s has no more explored zones.', NULL),
	(553, '%s has explored all zones for you.', NULL),
	(554, '%s has hidden all zones from you.', NULL),
	(557, '%s level up you to (%i)', NULL),
	(558, '%s level down you to (%i)', NULL),
	(559, '%s reset your level progress.', NULL),
	(560, 'The area has been set as explored.', NULL),
	(561, 'The area has been set as not explored.', NULL),
	(564, 'The value index %u is too big to %s (count: %u).', NULL),
	(565, 'Set for %s field:%u to uint32 value:%u', NULL),
	(566, 'You set for %s field:%u to uint32 value: %u', NULL),
	(567, 'Set for %s field:%u to to float value:%f', NULL),
	(568, 'You set for %s field:%u to float value: %f', NULL),
	(569, 'Get %s uint32 value:[FIELD]:%u [VALUE]:%u', NULL),
	(570, '%s has uint32 value:[FIELD]:%u [VALUE]:%u', NULL),
	(571, 'Get %s float value:[FIELD]:%u [VALUE]:%f', NULL),
	(572, '%s has float value:[FIELD]:%u [VALUE]:%f', NULL),
	(575, 'Modify %s uint32 field:%u to sum with:%i = %u (%i)', NULL),
	(576, 'You modify for %s uint32 field:%u to sum with:%i = %u (%i)', NULL),
	(577, 'You are now invisible.', NULL),
	(578, 'You are now visible.', NULL),
	(579, 'Selected player or creature not have victim.', NULL),
	(580, 'You learned all default spells for race/class and completed quests rewarded spells.', NULL),
	(581, 'Found near gameobjects (distance %f): %u ', NULL),
	(582, 'SpawnTime: Full:%s Remain:%s', NULL),
	(583, '%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s', NULL),
	(584, 'No event found!', NULL),
	(585, 'Event not exist!', NULL),
	(586, 'Event %u: %s%sStart: %s End: %s Occurence: %s Length: %sNext state change: %s', NULL),
	(587, 'Event %u already active!', NULL),
	(588, 'Event %u not active!', NULL),
	(589, '   Point movement to (X:%f Y:%f Z:%f)', NULL),
	(590, '   Fear movement', NULL),
	(591, '   Distract movement', NULL),
	(592, 'You have learned all spells in craft: %s', NULL),
	(593, 'Currently Banned Accounts:', NULL),
	(594, '|    Account    |   BanDate    |   UnbanDate  |  Banned By    |   Ban Reason  |', NULL),
	(595, 'Currently Banned IPs:', NULL),
	(596, '|      IP       |   BanDate    |   UnbanDate  |  Banned By    |   Ban Reason  |', NULL),
	(597, 'Current gamemasters:', NULL),
	(598, '|    Account    |  GM  |', NULL),
	(599, 'No gamemasters.', NULL),
	(600, 'The Alliance wins!', '联盟获胜!'),
	(601, 'The Horde wins!', '部落获胜!'),
	(602, 'The battle for Warsong Gulch begins in 1 minute.', '战歌峡谷战斗1分钟后开始.'),
	(603, 'The battle for Warsong Gulch begins in 30 seconds. Prepare yourselves!', '战歌峡谷战斗30秒后开始. 准备好了吧!'),
	(604, 'Let the battle for Warsong Gulch begin!', '战歌峡谷战斗开始!'),
	(605, '$n captured the Horde flag!', '$n夺取了部落旗帜!'),
	(606, '$n captured the Alliance flag!', '$n夺取了联盟旗帜!'),
	(607, 'The Horde flag was dropped by $n!', '部落旗帜被$n丢掉了!'),
	(608, 'The Alliance Flag was dropped by $n!', '联盟旗帜被$n丢掉了!'),
	(609, 'The Alliance Flag was returned to its base by $n!', '联盟旗帜被$n送回了基地!'),
	(610, 'The Horde flag was returned to its base by $n!', '部落旗帜被$n送回了基地!'),
	(611, 'The Horde flag was picked up by $n!', '部落旗帜被$n捡起来了!'),
	(612, 'The Alliance Flag was picked up by $n!', '联盟旗帜被$n捡起来了!'),
	(613, 'The flags are now placed at their bases.', '旗帜现在被放入它们基地.'),
	(614, 'The Alliance flag is now placed at its base.', '联盟旗帜现在被放入基地.'),
	(615, 'The Horde flag is now placed at its base.', '部落旗帜现在被放入基地.'),
	(650, 'Alliance', '联盟'),
	(651, 'Horde', '部落'),
	(652, 'stables', '兽栏'),
	(653, 'blacksmith', '铁匠铺'),
	(654, 'farm', '农场'),
	(655, 'lumber mill', '伐木场'),
	(656, 'mine', '矿洞'),
	(657, 'The %s has taken the %s', '%s夺取了%s'),
	(658, '$n has defended the %s', '$n守住了%s'),
	(659, '$n has assaulted the %s', '$n突袭了%s'),
	(660, '$n claims the %s! If left unchallenged, the %s will control it in 1 minute!', NULL),
	(661, 'The Battle for Arathi Basin begins in 1 minute.', NULL),
	(662, 'The Battle for Arathi Basin begins in 30 seconds. Prepare yourselves!', NULL),
	(663, 'The Battle for Arathi Basin has begun!', NULL),
	(664, 'The Alliance has gathered $1776W resources, and is near victory!', NULL),
	(665, 'The Horde has gathered $1777W resources, and is near victory!', NULL),
	(666, 'After your recent battle in %s our best attempts to award you a Mark of Honor failed. Enclosed you will find the Mark of Honor we were not able to deliver to you at the time. Thanks for fighting in %s!', NULL),
	(705, 'You must wait %s before speaking again.', NULL),
	(706, 'This item(s) has problems with equipping/storing to inventory.', NULL),
	(707, '%s does not wish to be disturbed: %s', NULL),
	(708, '%s is Away from Keyboard: %s', NULL),
	(709, 'Do not Disturb', NULL),
	(710, 'Away from Keyboard', NULL),
	(711, 'Queue status for %s (Lvl: %u to %u)Queued alliances: %u (Need at least %u more)Queued hordes: %u (Need at least %u more)', NULL),
	(712, '|cffff0000[BG Queue Announcer]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r', NULL),
	(715, 'You don\'t meet Battleground level requirements', NULL),
	(717, '|cffff0000[BG Queue Announcer]:|r %s -- [%u-%u] Started!|r', NULL),
	(720, 'Your group is too large for this battleground. Please regroup to join.', NULL),
	(727, 'Your group has an offline member. Please remove him before joining.', NULL),
	(728, 'Your group has players from the opposing faction. You can\'t join the battleground as a group.', NULL),
	(729, 'Your group has players from different battleground brakets. You can\'t join as group.', NULL),
	(730, 'Someone in your party is already in this battleground queue. (S)he must leave it before joining as group.', NULL),
	(731, 'Someone in your party is Deserter. You can\'t join as group.', NULL),
	(732, 'Someone in your party is already in three battleground queues. You cannot join as group.', NULL),
	(733, 'You cannot teleport to a battleground map.', NULL),
	(734, 'You cannot summon players to a battleground or arena map.', NULL),
	(735, 'You must be in GM mode to teleport to a player in a battleground.', NULL),
	(736, 'You cannot teleport to a battleground from another battleground. Please leave the current battleground first.', NULL),
	(739, 'Battlegrounds are set to 1v0 for debugging.', NULL),
	(740, 'Battlegrounds are set to normal playercount.', NULL),
	(750, 'Not enough players. This game will close in %u mins.', NULL),
	(751, 'Not enough players. This game will close in %u seconds.', NULL),
	(752, 'Only the Alliance can use that portal', NULL),
	(753, 'Only the Horde can use that portal', NULL),
	(759, '%s was destroyed by the %s!', NULL),
	(760, 'The %s is under attack! If left unchecked, the %s will destroy it!', NULL),
	(761, 'The %s was taken by the %s!', NULL),
	(762, 'The %s was taken by the %s!', NULL),
	(763, 'The %s was taken by the %s!', NULL),
	(764, 'The %s is under attack! If left unchecked, the %s will capture it!', NULL),
	(765, 'The %s has taken the %s! Its supplies will now be used for reinforcements!', NULL),
	(766, 'Irondeep Mine', NULL),
	(767, 'Coldtooth Mine', NULL),
	(768, 'Stormpike Aid Station', NULL),
	(769, 'Dun Baldar South Bunker', NULL),
	(770, 'Dun Baldar North Bunker', NULL),
	(771, 'Stormpike Graveyard', NULL),
	(772, 'Icewing Bunker', NULL),
	(773, 'Stonehearth Graveyard', NULL),
	(774, 'Stonehearth Bunker', NULL),
	(775, 'Snowfall Graveyard', NULL),
	(776, 'Iceblood Tower', NULL),
	(777, 'Iceblood Graveyard', NULL),
	(778, 'Tower Point', NULL),
	(779, 'Frostwolf Graveyard', NULL),
	(780, 'East Frostwolf Tower', NULL),
	(781, 'West Frostwolf Tower', NULL),
	(782, 'Frostwolf Relief Hut', NULL),
	(784, '1 minute until the battle for Alterac Valley begins.', NULL),
	(785, '30 seconds until the battle for Alterac Valley begins. Prepare yourselves!', NULL),
	(786, 'The battle for Alterac Valley has begun!', NULL),
	(787, 'The Alliance Team is running out of reinforcements!', NULL),
	(788, 'The Horde Team is running out of reinforcements!', NULL),
	(789, 'The Frostwolf General is Dead!', NULL),
	(790, 'The Stormpike General is Dead!', NULL),
	(801, 'You do not have enough gold', NULL),
	(802, 'You do not have enough free slots', NULL),
	(803, 'Your partner does not have enough free bag slots', NULL),
	(804, 'You do not have permission to perform that function', NULL),
	(805, 'Unknown language', NULL),
	(806, 'You don\'t know that language', NULL),
	(807, 'Please provide character name', NULL),
	(808, 'Player %s not found or offline', NULL),
	(809, 'Account for character %s not found', NULL),
	(811, 'Guild Master', NULL),
	(812, 'Officer', NULL),
	(813, 'Veteran', NULL),
	(814, 'Member', NULL),
	(815, 'Initiate', NULL),
	(1000, 'Exiting daemon...', NULL),
	(1001, 'Account deleted: %s', NULL),
	(1002, 'Account %s NOT deleted (probably sql file format was updated)', NULL),
	(1003, 'Account %s NOT deleted (unknown error)', NULL),
	(1004, 'Account created: %s', NULL),
	(1005, 'Account name cannot be longer than 16 characters (client limit), account not created!', NULL),
	(1006, 'Account with this name already exist!', NULL),
	(1007, 'Account %s NOT created (probably sql file format was updated)', NULL),
	(1008, 'Account %s NOT created (unknown error)', NULL),
	(1009, 'Player %s (Guid: %u) Account %s (Id: %u) deleted.', NULL),
	(1010, '| ID         |    Account    |       Character      |       IP        | GM | Expansion |', NULL),
	(1012, '========================================================================================', NULL),
	(1013, '| %10u |%15s| %20s | %15s |%4d| %9d |', NULL),
	(1014, 'No online players.', NULL),
	(1015, 'Can only quit from a Remote Admin console or the quit command was not entered in full (quit).', NULL),
	(1016, '| GUID       | Name                 | Account                      | Delete Date         |', NULL),
	(1017, '| %10u | %20s | %15s (%10u) | %19s |', NULL),
	(1018, '==========================================================================================', NULL),
	(1019, 'No characters found.', NULL),
	(1020, 'Restoring the following characters:', NULL),
	(1021, 'Deleting the following characters:', NULL),
	(1022, 'ERROR: You can only assign a new name for a single selected character!', NULL),
	(1023, 'Character \'%s\' (GUID: %u Account %u) can\'t be restored: account doesn\'t exist!', NULL),
	(1024, 'Character \'%s\' (GUID: %u Account %u) can\'t be restored: account character list full!', NULL),
	(1025, 'Character \'%s\' (GUID: %u Account %u) can\'t be restored: name already in use!', NULL),
	(1026, 'GUID: %u Name: %s Account: %s (%u) Date: %s', NULL),
	(1027, 'Log filters state:', NULL),
	(1028, 'All log filters set to: %s', NULL),
	(1029, 'Command can only be called from a Remote Admin console.', NULL),
	(1100, 'Account %s (Id: %u) has been granted %u expansion rights.', NULL),
	(1101, 'Message of the day changed to:%s', NULL),
	(1102, 'Message sent to %s: %s', NULL),
	(1103, '%d - %s %s', NULL),
	(1104, '%d - %s', NULL),
	(1105, '%d - %s %s', NULL),
	(1106, '%d - %s %s', NULL),
	(1107, '%d - %s', NULL),
	(1108, '%d - %s %s', NULL),
	(1109, '%d - %s %s %s %s', NULL),
	(1110, '%d%s - %s X:%f Y:%f Z:%f MapId:%d', NULL),
	(1111, '%d%s - %s X:%f Y:%f Z:%f MapId:%d', NULL),
	(1112, 'Failed to open file: %s', NULL),
	(1113, 'Account %s (%u) have max amount allowed characters (client limit)', NULL),
	(1114, 'Dump file have broken data!', NULL),
	(1115, 'Invalid character name!', NULL),
	(1116, 'Invalid character guid!', NULL),
	(1117, 'Character guid %u in use!', NULL),
	(1118, '%d - guild: %s (guid: %u) %s', NULL),
	(1119, 'You must use male or female as gender.', NULL),
	(1120, 'You change gender of %s to %s.', NULL),
	(1121, 'Your gender changed to %s by %s.', NULL),
	(1122, '(%u/%u +perm %u +temp %u)', NULL),
	(1128, '%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Map:%u X:%f Y:%f Z:%f)', NULL),
	(1129, '%d - %s %s (Map:%u X:%f Y:%f Z:%f)', NULL),
	(1130, 'event started %u \"%s\"', NULL),
	(1131, 'event stopped %u \"%s\"', NULL),
	(1132, '   Follow player %s (lowguid %u)', NULL),
	(1133, '   Follow creature %s (lowguid %u)', NULL),
	(1134, '   Follow <NULL>', NULL),
	(1135, 'List known talents:', NULL),
	(1136, '   (Found talents: %u used talent points: %u)', NULL),
	(1137, '%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ', NULL),
	(1138, '=================================================================================', NULL),
	(1139, '| GUID       | Name                 | Race            | Class           | Level |', NULL),
	(1140, '| %10u | %20s | %15s | %15s | %5u |', NULL),
	(1141, '%u - |cffffffff|Hplayer:%s|h[%s]|h|r %s %s %u', NULL),
	(1142, '%u - %s (Online:%s IP:%s GM:%u Expansion:%u)', NULL),
	(1143, 'Spawned by event %u (%s)', NULL),
	(1144, 'Despawned by event %u (%s)', NULL),
	(1145, 'Part of pool %u', NULL),
	(1146, 'Part of pool %u, top pool %u', NULL),
	(1147, 'The (top)pool %u is spawned by event %u (%s)', NULL),
	(1148, 'The (top)pool %u is despawned by event %u (%s)', NULL),
	(1149, ' (Pool %u)', NULL),
	(1150, ' (Event %i)', NULL),
	(1151, ' (Pool %u Event %i)', NULL),
	(1152, '[usable]', NULL),
	(1153, 'Get %s bitstr value:[FIELD]:%u [VALUE]:%s', NULL),
	(1154, '%s has bitstr value:[FIELD]:%u [VALUE]:%s', NULL),
	(1155, 'Get %s hex value:[FIELD]:%u [VALUE]:%x', NULL),
	(1156, '%s has hex value:[FIELD]:%u [VALUE]:%x', NULL),
	(1157, 'Modify %s hex field:%u %s %x = %x (hex)', NULL),
	(1158, 'You modify for %s hex field:%u %s %x = %x (hex)', NULL),
	(1159, 'Modify %s float field:%u to sum with:%f = %f', NULL),
	(1160, 'You modify for %s float field:%u to sum with:%f = %f', NULL),
	(1165, 'Spell %u not have auras.', NULL),
	(1166, 'Scripting library not found or not accessible.', NULL),
	(1167, 'Scripting library has wrong list functions (outdated?).', NULL),
	(1168, 'Scripting library reloaded.', NULL),
	(1169, 'Scripting library build for different mangosd revision.', NULL),
	(1171, 'All config are reloaded from ahbot configuration file.', NULL),
	(1172, 'Error while trying to reload ahbot config.', NULL),
	(1173, '==========================================================', NULL),
	(1174, '|--------------------------------------------------------|', NULL),
	(1175, '|            | Alliance |  Horde   | Neutral  |  Total   |', NULL),
	(1176, '          Alliance/Horde/Neutral/Total', NULL),
	(1177, '| %-10s | %8u | %8u | %8u | %8u |', NULL),
	(1178, '%-10s = %6u / %6u / %6u / %6u', NULL),
	(1179, 'Count', NULL),
	(1180, 'Item Ratio', NULL),
	(1181, '|            | Alliance |   Horde  | Neutral  |  Amount  |', NULL),
	(1182, '          Alliance/Horde/Neutral/Amount', NULL),
	(1183, 'Grey', NULL),
	(1184, 'White', NULL),
	(1185, 'Green', NULL),
	(1186, 'Blue', NULL),
	(1187, 'Purple', NULL),
	(1188, 'Orange', NULL),
	(1189, 'Yellow', NULL),
	(1190, 'Amount of %s items is set to %u.', NULL),
	(1191, 'Items ratio for %s is set to %u.', NULL),
	(1192, 'Effect movement', NULL),
	(1194, 'Current State Information: GOState %u, LootState %u. Collision %s', NULL),
	(1195, 'Current State Information: GOState %u, LootState %u. Collision %s, (door %s by default)', NULL),
	(1200, 'You try to view cinematic %u but it doesn\'t exist.', NULL),
	(1202, 'Spell %u %s = %f (*1.88 = %f) DB = %f AP = %f', NULL),
	(1203, 'direct heal', NULL),
	(1204, 'direct damage', NULL),
	(1205, 'dot heal', NULL),
	(1206, 'dot damage', NULL),
	(1400, 'Private ', NULL),
	(1401, 'Corporal ', NULL),
	(1402, 'Sergeant ', NULL),
	(1403, 'Master Sergeant ', NULL),
	(1404, 'Sergeant Major ', NULL),
	(1405, 'Knight ', NULL),
	(1406, 'Knight-Lieutenant ', NULL),
	(1407, 'Knight-Captain ', NULL),
	(1408, 'Knight-Champion ', NULL),
	(1409, 'Lieutenant Commander ', NULL),
	(1410, 'Commander ', NULL),
	(1411, 'Marshal ', NULL),
	(1412, 'Field Marshal ', NULL),
	(1413, 'Grand Marshal ', NULL),
	(1414, 'Scout ', NULL),
	(1415, 'Grunt ', NULL),
	(1416, 'Sergeant ', NULL),
	(1417, 'Senior Sergeant ', NULL),
	(1418, 'First Sergeant ', NULL),
	(1419, 'Stone Guard ', NULL),
	(1420, 'Blood Guard ', NULL),
	(1421, 'Legionnare ', NULL),
	(1422, 'Centurion ', NULL),
	(1423, 'Champion ', NULL),
	(1424, 'Lieutenant General ', NULL),
	(1425, 'General ', NULL),
	(1426, 'Warlord ', NULL),
	(1427, 'High Warlord ', NULL),
	(1428, 'Game Master ', NULL),
	(1429, 'No Rank ', NULL),
	(1430, 'Dishonored ', NULL),
	(1431, 'Exiled ', NULL),
	(1432, 'Outlaw ', NULL),
	(1433, 'Pariah ', NULL),
	(1434, 'Player: %s - %s (Rank %u)', NULL),
	(1435, 'Today: [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r]', NULL),
	(1436, 'Yesterday: [Kills: |c0000ff00%u|r] [Honor: %u]', NULL),
	(1437, 'This Week: [Kills: |c0000ff00%u|r] [Honor: %u]', NULL),
	(1438, 'Last Week: [Kills: |c0000ff00%u|r] [Honor: %u] [Standing: %u]', NULL),
	(1439, 'Life Time: [Rank Points: |c0000ff00%f|r] [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r] [Highest Rank %u: %s]', NULL),
	(1500, '%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s', NULL),
	(1501, '%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u %s', NULL),
	(1502, '%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u %s', NULL),
	(1503, 'Cannot add spawn because no free guids for static spawn in reserved guids range. Server restart is required before command can be used. Also look GuidReserveSize.* config options.', NULL),
	(1504, 'AI-Information for Npc Entry %u', NULL),
	(1505, 'AIName: %s (%s) ScriptName: %s', NULL),
	(1506, 'Current phase = %u', NULL),
	(1507, 'Combat-Movement is %s', NULL),
	(1508, 'Melee attacking is %s', NULL),
	(1509, 'Pool %u not found (Maximal pool entry is %u)', NULL),
	(1600, '|cffffff00Northpass Tower has been taken by the Horde!|r', NULL),
	(1601, '|cffffff00Northpass Tower has been taken by the Alliance!|r', NULL),
	(1602, '|cffffff00Crown Guard Tower has been taken by the Horde!|r', NULL),
	(1603, '|cffffff00Crown Guard Tower has been taken by the Alliance!|r', NULL),
	(1604, '|cffffff00Eastwall Tower has been taken by the Horde!|r', NULL),
	(1605, '|cffffff00Eastwall Tower has been taken by the Alliance!|r', NULL),
	(1606, '|cffffff00The Plaguewood Tower has been taken by the Horde!|r', NULL),
	(1607, '|cffffff00The Plaguewood Tower has been taken by the Alliance!|r', NULL),
	(1635, '|cffffff00The Horde has collected 200 silithyst!|r', NULL),
	(1636, '|cffffff00The Alliance has collected 200 silithyst!|r', NULL),
	(1510, 'Closed ticket for player %s', NULL),
	(1511, 'Ticket system is globally on, accepting all tickets', NULL),
	(1512, 'Ticket system is globally off, not accepting tickets at all', NULL),
	(1513, 'You cant close a ticket for offline players', NULL),
	(241, 'Waypoint removed.', NULL),
	(242, 'UNUSED', NULL),
	(243, 'UNUSED', NULL),
	(244, 'UNUSED', NULL),
	(245, 'UNUSED', NULL),
	(246, 'Waypoint %u for %s (from pathId %i, stored by %s)', NULL),
	(247, ' Waittime: %d', NULL),
	(248, ' Orientation: %f', NULL),
	(249, ' ScriptId: %u', NULL),
	(250, 'ScriptID set to non-existing id %u, add it to DBScriptsEngine and reload the table.', NULL),
	(251, 'UNUSED', NULL),
	(252, 'AIScriptName: %s', NULL);
